example_key: ENC[AES256_GCM,data:ii7o/N0YEeUOZ6KXQQ==,iv:EztyFYhsu2yjhqmkb2LkMSvD0/D5LOWU3z5mTy/ooB8=,tag:XlmAiGZURviWqs7MyRkcbw==,type:str]
sops:
    age:
        - recipient: age18dv6f9zy7xadup7txek3uyma6fx2a3lfamaxcd4dzmphf620aeesg6eram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXlWdFRmQmh6dlArQ1NJ
            MVNTTGZrTll4QXNjbW8vMXF2cHBvUWlISmpnCkRvVmlmZ3B0RlJUbSsyNU1VK29k
            R3VHcC9aUU5BYzUwblk3UlFQWTRsb1UKLS0tIE53V0lsd2J5WnNEVGR6TExFVnVE
            L2IyTEtETUl2c3pQVStZNWdpVG00dG8Kb1wja+tDZPwrGlXsp55LhgFTVZJG9FTG
            oBBBMX30Eue6nPFR+g7fmW3pfu8X2PDEorFz1PsMNa+iNp1Yk6In0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acgas9zrcku7pner4vqmm64l8435uf3tt92psrd0lwx9zh7y6gjsdfgtxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cUVHTzhrWEtqYXVCMlNM
            OTVaOE5waSswWlJiRXMxS1QwZGwwVzFvM3p3CmR6a0FvZDdBekRrOWI0emNQd1dv
            QlRGS2hINHBJdUg2NUJ4REVycnNBUVUKLS0tIGNDVnQvV0d4ZExpdzlzZ2s2bFA0
            L0h2NldVNU1HNytPaEZ6RnBOamhWcHMKKw+yKR5XUMRShzXiRgSf9O9LkdRc/dVG
            M5N0DAYjLZOHCGg0AADmzuzYdYgbXISyZKffB8ZG7+FyVVQiwifJ6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10eysz9tmpa22gkgr3ulmmmy870q4gcukwl4enxqp4r8y8wp8lpxsmmuyq7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWWdrVEpBLzhmY2JMdWFY
            OUE3elY1WGF3a3lBY2grb2hLMUNja3VNNUhZCkRvNVhzRjZTbkc1Mk1UM25KQ3Q3
            WFF4V01UeDBNMzJ2MnR0djdVaTVLaUUKLS0tIFBjRzdhM01XamVTTnBEOWVNeWpP
            djJ0ZlRkSWYrdlg3Z0tZMXRCK0ZuWWcKrgKpFFS2ZLFxCGSKrPbXr3FKA+lMPJuM
            C2xuE+Du9RSP6LqgjtF96ddahjB9hi1Iji2D8Wvl311x9gHtPs95dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T17:44:34Z"
    mac: ENC[AES256_GCM,data:kSj3LimbeCXsY+WlfeeXLeswGOEe8Osr84/zQIulVM3TsAr7mTSjmAbm9EStQ8Zbq92CGw6bmDOH6xnMZAIUg7rN/ftM54B2hN/X/qAoLuiRwP79oz+IqU8BjNYXmuq5n8bPr7HZ8Q1bwq20JwNtYpz/DdQfEGkULjkbVhhHuW4=,iv:/TYDxHc63Xd96Np3gvziOA3O1V4ERATBMzOifrSd3aw=,tag:FgxFQ6qhgVtqcnmppEiU7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
