example_key: ENC[AES256_GCM,data:ii7o/N0YEeUOZ6KXQQ==,iv:EztyFYhsu2yjhqmkb2LkMSvD0/D5LOWU3z5mTy/ooB8=,tag:XlmAiGZURviWqs7MyRkcbw==,type:str]
sops:
    age:
        - recipient: age18dv6f9zy7xadup7txek3uyma6fx2a3lfamaxcd4dzmphf620aeesg6eram
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb0pncGg4NzhWVG9FVis5
            MUZiSHRGdEFMY0N6YkFZZUQvM005ZUJzWlU0CmFna0llZjY1eGtoS25LMW96RDUz
            cjRIOG82c0Z5cjFpWm12cklZWEF3S0EKLS0tIC9DNUZYWkJsUGpIV1ZjYzVHeXlZ
            VlhCRkd3TjMyeU9RY1NWakh0bmw4cDAKdPbooRidHvfAfjF7WzueO36Iiwg42nPx
            UgOllwBwYWGitG5GyUYbzO4xU0pI+TzC+jpRrc9Luq1IlHenaLpljg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T17:44:34Z"
    mac: ENC[AES256_GCM,data:kSj3LimbeCXsY+WlfeeXLeswGOEe8Osr84/zQIulVM3TsAr7mTSjmAbm9EStQ8Zbq92CGw6bmDOH6xnMZAIUg7rN/ftM54B2hN/X/qAoLuiRwP79oz+IqU8BjNYXmuq5n8bPr7HZ8Q1bwq20JwNtYpz/DdQfEGkULjkbVhhHuW4=,iv:/TYDxHc63Xd96Np3gvziOA3O1V4ERATBMzOifrSd3aw=,tag:FgxFQ6qhgVtqcnmppEiU7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
